deployment:
  tasks:
    - export DEPLOYPATH=/home1/fabi4954/comfortable-yellow-gorilla.192-185-222-24.cpanel.site/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH